### ISSUE TITLE
Issues about TaskInfo Sensor to be corrected

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-vsphere#12]
TaskInfo Sensor have some problems to be fixed about handling uncompleted task.

- When an uncompleted task is arrived, TaskInfoSensor will be crashed because of converting datetime object without verifying (Sorry, It's a bug that I made).
- We can't know when it is completed and what the result of it is.

**Comment by LindsayHill** [comment]
Addressed with #13 now merged
