### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by nzlosh** [StackStorm-Exchange/stackstorm-vsphere#79]
This pack doesn't support python3 because it's pinned explicitly to support python2.7.  When the underlying library is called from Python3 code exceptions are raised.  Since python2.7 is deprecated and StackStorm is removing python2.7 in v3.4, this pack should drop support for python2.7 and favour supporting python3.

**Comment by geluyan** [comment]
any news on this? v3.4 has released yesterday.

**Comment by arm4b** [comment]
@cognifloyd @nzlosh  do you think we're good here and the issue could be closed or some work is needed here?

**Comment by bishopbm1** [comment]
I don't believe this issue has been solved. I will be working through upgrading our internal environment this week. We use this pack heavily and will get it pushed to python3 then close this issue after making a PR.

**Comment by arm4b** [comment]
Thanks @bishopbm1!

**Comment by bishopbm1** [comment]
This has been tested and is closed by PR #85

**Comment by nzlosh** [comment]
:heart: Great job! @bishopbm1
