### ISSUE TITLE
requests.cookies.CookieConflictError: There are multiple cookies with name, 'vmware-api-session-id'

### ISSUE THREAD

**Issue by dsbibby** [StackStorm-Exchange/stackstorm-vsphere#87]
As previously seen in #83 I have been getting the error "There are multiple cookies with name, 'vmware-api-session-id'" with a new install of StackStorm 3.5 on CentOS 7.9

In debugging this I discovered [VMware KB 78315](https://kb.vmware.com/s/article/78315) that states cookie based authentication to the vSphere REST APIs is deprecated.

I have tested (and will submit a PR) moving to header based authentication for the REST API and it resolves the issue mentioned aboev also.

**Comment by bjarneeins** [comment]
I can confirm that the attached PR does fix this issue. Previous attempts did not. (Stackstorm 3.6 on + vsphere 7)

**Comment by arm4b** [comment]
@bjarneeins Thanks for checking!

@StackStorm-Exchange/encoretechnologies can someone please help reviewing and merging the https://github.com/StackStorm-Exchange/stackstorm-vsphere/pull/88?
