### ISSUE TITLE
Need to update README to fit the actual implementation

### ISSUE THREAD

**Issue by userlocalhost** [StackStorm-Exchange/stackstorm-vsphere#9]
Current README is differ from implementation. I think We needs to 

- update description about Actions. There are 12 description of action in the current README, but actually 22 actions are implemented.
- add description about Sensors. Currently, no description about sensors exists.
- update description about Configuration. There is no description about the parameters for sensors.

**Comment by LindsayHill** [comment]
Resolved with #9 - thanks!

**Comment by userlocalhost** [comment]
Thank you for closing.

**Comment by LindsayHill** [comment]
@userlocalhost we're the ones thanking you: you are doing great work. Drop me a line at lhill@brocade.com and we'll see if we can ship you some StackStorm swag!
